export const SIGNIN = 'signed'
export const VIEW = 'view'
export const UPDATE = 'update'
export const DELETE = 'delete'
export const ADD = 'add'
export const ADDVIEW = 'addview'
export const ADDTEAM = 'addteam'
export const POP = 'pop'
